name: powerpc/clang

# Controls when the action will run.
on:
  # This allows the build to be triggered manually via the github UI.
  workflow_dispatch:

  push:
    # This triggers the build on a push to any branch
    branches:
    - '**'
    # As long as one of these paths matches
    paths:
      - '!tools/**'		   	# ignore tools
      - '!samples/**'		   	# ignore samples
      - '!Documentation/**'		# ignore Documentation
      - '!arch/**'			# ignore arch changes
      - 'arch/powerpc/**'		# but not arch/powerpc
      - 'arch/Kconfig'			# or common bits in arch
      - '**'				# anything else triggers a build

jobs:
  kernel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      FIXME_CLANG: 1
      FIXME_ARCH: x86
      TARGET: kernel

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: bash ./ci-build.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-artifacts
        path: |
          ~/output/vmlinux
          ~/output/.config
          ~/output/System.map
          ~/output/modules.tar.bz2
          ~/output/arch/x86/boot/zImage
